FROM docker.io/texlive/texlive:latest-full

RUN tlmgr paper a4

RUN apt-get update \
    && apt-get install -y --no-install-recommends git=* p7zip-full=* locales=* locales-all=* \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
